### ISSUE TITLE
运行convert.py转fp16的时候，显示ValueError: unknown format: models/Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin

### ISSUE THREAD

**Issue by Congcong-Song** [ouwei2013/baichuan13b.cpp#9]
Loading model file models/Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/baichuan13b.cpp/convert.py", line 1263, in <module>
    main()
  File "/home/inspur/scc/gpt/baichuan13b.cpp/convert.py", line 1243, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inspur/scc/gpt/baichuan13b.cpp/convert.py", line 1164, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/inspur/scc/gpt/baichuan13b.cpp/convert.py", line 962, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: models/Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin

识别不了bin文件

**Comment by Congcong-Song** [comment]
@functools.lru_cache(maxsize=None)
def lazy_load_file(path: Path) -> ModelPlus:
    fp = open(path, 'rb')
    first8 = fp.read(8)
    fp.seek(0)
    if first8[:2] == b'PK':
        # A zip file, i.e. PyTorch format
        return lazy_load_torch_file(fp, path)
    elif first8[2:4] == b'gg':
        # GGML format
        return lazy_load_ggml_file(fp, path)
    elif struct.unpack('<Q', first8)[0] < 16 * 1024 * 1024:
        # Probably safetensors
        return lazy_load_safetensors_file(fp, path)
    else:
        raise ValueError(f"unknown format: {path}")

是这里出的错，没有bin文件相关标识

**Comment by ouwei2013** [comment]
是不是下载的文件损坏了？

CongcongSong ***@***.***>于2023年8月31日 周四14:57写道：

**Comment by Congcong-Song** [comment]
是的，刚检查了是文件损坏了。新下载后为什么convert后是models/Baichuan-13B-Chat/ggml-model-f32.bin呢？看后面的要求应该是f16才对
